spring:
  application:
    name: spring-jpa-test
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: qwer1234
    url: jdbc:postgresql://localhost:5433/springJpa
    hikari:
      connection-test-query: SELECT 1
      idle-timeout: 30000
      connection-timeout: 30000
      schema: public
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
logging:
  config: classpath:log4j2.xml
