spring:
  application:
    name: spring-jpa-test
  profiles:
    active: local
  jpa:
#    hibernate:
#      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
logging:
  config: classpath:log4j2.xml

