spring:
  application:
    name: springWebSocket
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
    web:
      pageable:
        one-indexed-parameters: false
logging:
  config: classpath:log4j2.xml

