
/* Drop Tables */

DROP TABLE TB_SAMPLE_FOOD_ORDER_ITEM CASCADE CONSTRAINTS;
DROP TABLE TB_SAMPLE_FOOD_ORDERS CASCADE CONSTRAINTS;
DROP TABLE TB_SAMPLE_CUSTOMERS CASCADE CONSTRAINTS;
DROP TABLE TB_SAMPLE_FOODS CASCADE CONSTRAINTS;
DROP TABLE TB_SAMPLE_FOOD_CATEGORY CASCADE CONSTRAINTS;




/* Create Tables */

CREATE TABLE TB_SAMPLE_CUSTOMERS
(
	CUSTOMER_NO number(4,0) NOT NULL,
	CUSTOMER_NAME varchar2(100) NOT NULL,
	CUSTOMER_TEL varchar2(20) UNIQUE,
	CUSTOMER_POINT number(7,0),
	CUSTOMER_IN_OUT varchar2(10),
	CUSTOMER_CREATED_DATE date DEFAULT SYSDATE,
	PRIMARY KEY (CUSTOMER_NO)
);


CREATE TABLE TB_SAMPLE_FOODS
(
	FOOD_NO number(4,0) NOT NULL,
	FOOD_PRICE number(7,0),
	FOOD_NAME varchar2(200) NOT NULL,
	FOOD_STOCK number(4,0),
	FOOD_ON_SALE varchar2(30) DEFAULT '''판매중''',
	CATEGORY_NO number(4,0) NOT NULL,
	PRIMARY KEY (FOOD_NO)
);


CREATE TABLE TB_SAMPLE_FOOD_CATEGORY
(
	CATEGORY_NO number(4,0) NOT NULL,
	CATEGORY_NAME varchar2(100) NOT NULL,
	PRIMARY KEY (CATEGORY_NO)
);


CREATE TABLE TB_SAMPLE_FOOD_ORDERS
(
	ORDER_NO number(7,0) NOT NULL,
	CUSTOMER_NO number(4,0) NOT NULL,
	ORDER_CREATED_DATE date DEFAULT SYSDATE NOT NULL,
	ORDER_STATUS varchar2(30) DEFAULT '''주문완료''',
	ORDER_TOTAL_PRICE number(7,0),
	PRIMARY KEY (ORDER_NO)
);


CREATE TABLE TB_SAMPLE_FOOD_ORDER_ITEM
(
	ORDER_NO number(7,0) NOT NULL,
	FOOD_NO number(4,0) NOT NULL,
	FOOD_AMOUNT number(2,0)
);



/* Create Foreign Keys */

ALTER TABLE TB_SAMPLE_FOOD_ORDERS
	ADD FOREIGN KEY (CUSTOMER_NO)
	REFERENCES TB_SAMPLE_CUSTOMERS (CUSTOMER_NO)
;


ALTER TABLE TB_SAMPLE_FOOD_ORDER_ITEM
	ADD FOREIGN KEY (FOOD_NO)
	REFERENCES TB_SAMPLE_FOODS (FOOD_NO)
;


ALTER TABLE TB_SAMPLE_FOODS
	ADD FOREIGN KEY (CATEGORY_NO)
	REFERENCES TB_SAMPLE_FOOD_CATEGORY (CATEGORY_NO)
;


ALTER TABLE TB_SAMPLE_FOOD_ORDER_ITEM
	ADD FOREIGN KEY (ORDER_NO)
	REFERENCES TB_SAMPLE_FOOD_ORDERS (ORDER_NO)
;



